# Project: test4-1
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = test4-1/main.o
LINKOBJ  = test4-1/main.o
LIBS     = -L"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/lib" -L"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/include" -I"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/include" -I"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/CompileSoftware/Dev-C+++5.9.2+±„–Ø∞Ê/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = test4-1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

test4-1/main.o: test4-1/main.cpp
	$(CPP) -c test4-1/main.cpp -o test4-1/main.o $(CXXFLAGS)
